"""
Exercise 11.10. Two words are “rotate pairs” if you can rotate one of them and get the other
Write a program that reads a wordlist and finds all the rotate pairs.

Status: need help
"""

from rotate import rotate_word

def make_word_dict(): # reads a word list and returns a dictionary with the words as keys
    d = dict()  # creates new dictionary where words will be stored
    fin = open('words.txt')
    for line in fin:
        word = line.strip().lower()  # need to strip whitespace and line before storing as a key in the dictionary
        d[word] = word
    return d

def rotate_pairs(word, word_dict): # prints all words that can be generated by rotating the word
    pairs_list = []
    for word in word_dict:
        for i in range(1, 26):  # do this 26 times
            if rotate.rotate_word
